package org.mycorp.models;

public enum StationStateEnum {
    AVAILABLE,
    AUTHORISATION,
    AUTHORIZED,
    WAIT_EV_REQUEST,
    START_CHARGING,
    EV_CHARGING_STATUS_REQUEST,
    EV_END_SESSION,
    CSMS_DECLINE_CHARGE,
    EV_DECLINE_CHARGE,
    UNAUTHORIZED,
    WAIT_CHARGING_REQUEST,
    PREPARED,
    CHARGING,
    STOP_CHARGING
}
